import type { Transaction } from "./types";
import { naira, TXN_META, formatDateTime } from "./data";

function esc(value: string) {
  return value.replace(/[&<>"]/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : "&quot;",
  );
}

/** The signed, human-readable amount for a receipt, e.g. "−₦7,500". */
export function signedAmount(txn: Transaction) {
  return `${txn.amount < 0 ? "−" : "+"}${naira(txn.amount)}`;
}

/**
 * Print a single transaction as a clean, standalone receipt. Renders the receipt
 * into a hidden iframe and calls print() on just that document, so the browser's
 * print dialog (with "Save as PDF") outputs the receipt alone — no app chrome,
 * no popup that can be blocked.
 */
export function printReceipt(txn: Transaction) {
  const rows: [string, string][] = [
    ["Reference", txn.reference],
    ["Description", txn.title],
    ["Details", txn.detail],
    ["Type", TXN_META[txn.type].label],
    ["Payment method", txn.method],
    ["Date", formatDateTime(txn.date)],
    ["Status", txn.status.charAt(0).toUpperCase() + txn.status.slice(1)],
  ];

  const rowsHtml = rows
    .map(
      ([label, value]) => `
        <tr>
          <td class="label">${esc(label)}</td>
          <td class="value">${esc(value)}</td>
        </tr>`,
    )
    .join("");

  const html = `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Duevy receipt ${esc(txn.reference)}</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          color: #14201b; padding: 40px; -webkit-print-color-adjust: exact; print-color-adjust: exact;
        }
        .sheet { max-width: 520px; margin: 0 auto; border: 1px solid #e3ebe7; border-radius: 20px; overflow: hidden; }
        .head { background: #0b6e4f; color: #fff; padding: 28px 32px; }
        .brand { font-size: 20px; font-weight: 700; letter-spacing: -0.02em; }
        .kind { margin-top: 4px; font-size: 12px; opacity: 0.85; text-transform: uppercase; letter-spacing: 0.08em; }
        .amount { margin-top: 20px; font-size: 34px; font-weight: 700; letter-spacing: -0.02em; }
        .body { padding: 8px 32px 20px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 12px 0; border-bottom: 1px solid #eef3f1; font-size: 13px; vertical-align: top; }
        tr:last-child td { border-bottom: none; }
        .label { color: #6b7b74; width: 42%; }
        .value { color: #14201b; font-weight: 600; text-align: right; }
        .foot { padding: 18px 32px 28px; color: #8a9791; font-size: 11px; text-align: center; }
        @media print { body { padding: 0; } .sheet { border: none; } }
      </style>
    </head>
    <body>
      <div class="sheet">
        <div class="head">
          <div class="brand">Duevy.</div>
          <div class="kind">Payment receipt</div>
          <div class="amount">${esc(signedAmount(txn))}</div>
        </div>
        <div class="body">
          <table>${rowsHtml}</table>
        </div>
        <div class="foot">
          This is a computer-generated receipt and needs no signature.<br/>
          Generated by Duevy · duevy.app
        </div>
      </div>
    </body>
  </html>`;

  const frame = document.createElement("iframe");
  frame.style.position = "fixed";
  frame.style.right = "0";
  frame.style.bottom = "0";
  frame.style.width = "0";
  frame.style.height = "0";
  frame.style.border = "0";
  document.body.appendChild(frame);

  const doc = frame.contentWindow?.document;
  if (!doc) {
    document.body.removeChild(frame);
    return;
  }
  doc.open();
  doc.write(html);
  doc.close();

  const win = frame.contentWindow;
  if (!win) return;
  // Give the iframe a tick to lay out before printing, then clean up.
  win.focus();
  setTimeout(() => {
    win.print();
    setTimeout(() => document.body.removeChild(frame), 500);
  }, 150);
}
