import type { CollectionStudent, StatusFilter } from "./types";

export const COLLECTION_STUDENTS: CollectionStudent[] = [
  {
    id: "std-1",
    name: "Amina Bello",
    matricNo: "CSC/21/1042",
    level: "400L",
    email: "amina.bello@student.edu",
    status: "paid",
    paidAt: "Today, 10:12 AM",
    reference: "DVY-842901",
  },
  {
    id: "std-2",
    name: "Daniel Okafor",
    matricNo: "CSC/22/1176",
    level: "300L",
    email: "daniel.okafor@student.edu",
    status: "paid",
    paidAt: "Today, 9:04 AM",
    reference: "DVY-842765",
  },
  {
    id: "std-3",
    name: "Rukayat Yusuf",
    matricNo: "CSC/23/1288",
    level: "200L",
    email: "rukayat.yusuf@student.edu",
    status: "paid",
    paidAt: "Yesterday",
    reference: "DVY-841932",
  },
  {
    id: "std-4",
    name: "Samuel Udo",
    matricNo: "CSC/24/1431",
    level: "100L",
    email: "samuel.udo@student.edu",
    status: "unpaid",
  },
  {
    id: "std-5",
    name: "Ifeoma Nwosu",
    matricNo: "CSC/22/1190",
    level: "300L",
    email: "ifeoma.nwosu@student.edu",
    status: "paid",
    paidAt: "Mon, 4:38 PM",
    reference: "DVY-840558",
  },
  {
    id: "std-6",
    name: "Tobi Adebayo",
    matricNo: "CSC/23/1315",
    level: "200L",
    email: "tobi.adebayo@student.edu",
    status: "unpaid",
  },
  {
    id: "std-7",
    name: "Grace Etim",
    matricNo: "CSC/24/1408",
    level: "100L",
    email: "grace.etim@student.edu",
    status: "unpaid",
  },
  {
    id: "std-8",
    name: "Malik Hassan",
    matricNo: "CSC/21/1028",
    level: "400L",
    email: "malik.hassan@student.edu",
    status: "paid",
    paidAt: "Fri, 1:20 PM",
    reference: "DVY-839114",
  },
];

export const COLLECTION_TABS: { value: StatusFilter; label: string }[] = [
  { value: "all", label: "All" },
  { value: "paid", label: "Paid" },
  { value: "unpaid", label: "Unpaid" },
];
