import { formatDateTime } from "../../transactions/_components/data";
import { naira, PAYOUT_STATUS_META } from "./data";
import type { Payout } from "./types";

function esc(value: string) {
  return value.replace(/[&<>"]/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : "&quot;",
  );
}

/**
 * Print one withdrawal as a standalone receipt (the browser's print dialog
 * offers "Save as PDF"). There's no server-side payout receipt, so this renders
 * into a hidden iframe — same approach as the transactions receipt — with the
 * doodle artwork as the header.
 */
export function printPayoutReceipt(payout: Payout, spaceName: string) {
  const rows: [string, string][] = [
    ["Department", spaceName],
    ["Sent to", payout.accountName ?? "—"],
    ["Account", payout.account],
    ["Amount", naira(payout.amount)],
    ["Withdrawal fee", payout.fee > 0 ? `−${naira(payout.fee)}` : "Free"],
    ["Received by bank", naira(payout.net)],
    ["Reference", payout.reference],
    ["Requested", formatDateTime(payout.timeline.requestedAt)],
    ...(payout.timeline.settledAt
      ? ([["Paid out", formatDateTime(payout.timeline.settledAt)]] as [string, string][])
      : []),
    ["Status", PAYOUT_STATUS_META[payout.status].label],
  ];

  const rowsHtml = rows
    .map(
      ([label, value]) => `
        <tr${label === "Received by bank" ? ' class="strong"' : ""}>
          <td class="label">${esc(label)}</td>
          <td class="value">${esc(value)}</td>
        </tr>`,
    )
    .join("");

  const doodle = `${window.location.origin}/doodle-card.jpg`;
  const html = `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Duevy withdrawal ${esc(payout.reference)}</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          color: #14201b; padding: 40px; -webkit-print-color-adjust: exact; print-color-adjust: exact;
        }
        .sheet { max-width: 520px; margin: 0 auto; border: 1px solid #e3ebe7; border-radius: 20px; overflow: hidden; }
        .head { background: #08583f url("${doodle}") center / cover no-repeat; color: #fff; padding: 28px 32px; }
        .top { display: flex; justify-content: space-between; align-items: center; }
        .brand { font-size: 20px; font-weight: 700; letter-spacing: -0.02em; }
        .pill { font-size: 11px; font-weight: 600; background: rgba(255,255,255,0.18); padding: 4px 10px; border-radius: 999px; }
        .kind { margin-top: 18px; font-size: 12px; opacity: 0.8; text-transform: uppercase; letter-spacing: 0.08em; }
        .amount { margin-top: 6px; font-size: 34px; font-weight: 700; letter-spacing: -0.02em; }
        .to { margin-top: 6px; font-size: 13px; opacity: 0.85; }
        .body { padding: 8px 32px 20px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 12px 0; border-bottom: 1px solid #eef3f1; font-size: 13px; vertical-align: top; }
        tr:last-child td { border-bottom: none; }
        .label { color: #6b7b74; width: 42%; }
        .value { color: #14201b; font-weight: 600; text-align: right; word-break: break-all; }
        tr.strong .value { color: #0b6e4f; font-size: 15px; font-weight: 700; }
        .foot { padding: 18px 32px 28px; color: #8a9791; font-size: 11px; text-align: center; }
        @media print { body { padding: 0; } .sheet { border: none; } }
      </style>
    </head>
    <body>
      <div class="sheet">
        <div class="head">
          <div class="top">
            <div class="brand">Duevy.</div>
            <div class="pill">${esc(PAYOUT_STATUS_META[payout.status].label)}</div>
          </div>
          <div class="kind">Withdrawal receipt</div>
          <div class="amount">${esc(naira(payout.amount))}</div>
          <div class="to">to ${esc(payout.accountName ?? payout.account)}</div>
        </div>
        <div class="body">
          <table>${rowsHtml}</table>
        </div>
        <div class="foot">
          This is a computer-generated receipt and needs no signature.<br/>
          Generated by Duevy · duevy.app
        </div>
      </div>
    </body>
  </html>`;

  const frame = document.createElement("iframe");
  frame.style.position = "fixed";
  frame.style.right = "0";
  frame.style.bottom = "0";
  frame.style.width = "0";
  frame.style.height = "0";
  frame.style.border = "0";
  document.body.appendChild(frame);

  const win = frame.contentWindow;
  const doc = win?.document;
  if (!win || !doc) {
    document.body.removeChild(frame);
    return;
  }
  doc.open();
  doc.write(html);
  doc.close();

  // Print once the header artwork has loaded (or after a short cap), so the
  // PDF doesn't come out with a blank header.
  let printed = false;
  const print = () => {
    if (printed) return;
    printed = true;
    win.focus();
    win.print();
    setTimeout(() => document.body.removeChild(frame), 500);
  };
  const img = new Image();
  img.onload = () => setTimeout(print, 50);
  img.onerror = print;
  img.src = doodle;
  setTimeout(print, 1500);
}
